# https://docs.github.com/en/free-pro-team@latest/actions/creating-actions/metadata-syntax-for-github-actions
name: Deploy action stuff

description: Modified template action.yml file in an attempt to get stuff working.

author: Moosterbox

inputs:
  VITE_TBA_API_KEY:
    description: TBA key required for github webpage.
    default: ${{ github.token }}
    required: false

#outputs:
#  result:
#    description: action result

branding:
   https://turbotrojans-3302.github.io/blackhawks-scouting/
  # e.g. https://haya14busa.github.io/github-action-brandings/
  icon: 'package'
  color: 'orange'

runs:
  using: 'node20'
  main: 'main.js'
#  pre: lib/pre.js
#  pre-if: 'runner.os == linux'
#  post: lib/post.js
#  post-if: 'success()'
