# https://docs.github.com/en/free-pro-team@latest/actions/creating-actions/metadata-syntax-for-github-actions
name: Deploy action stuff

description: Modified template action.yml file in an attempt to get stuff working.

author: Moosterbox


#outputs:
#  result:
#    description: action result

runs:
  using: "composite"
  steps:
    - run: cd ${{ github.action_path }}
      shell: bash
#  pre: lib/pre.js
#  pre-if: 'runner.os == linux'
#  post: lib/post.js
#  post-if: 'success()'
